name: Webpack

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20

    - run: npm ci
    - run: npm test
    - run: npm run build

    - name: Publish Test Summary Results
      run: npx github-actions-ctrf ctrf/ctrf-report.json
      if: success() || failure()

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      if: success() || failure()
      with:
        path: /coverage
