name: Webpack

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - run: npm ci
    - run: npm test
    - run: npm run build

    - name: Publish Test Summary Results
      run: npx github-actions-ctrf ctrf/ctrf-report.json
